import { Box } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import {
  CallToAction,
  Contact,
  FeatureList,
  Hero,
  Statistic,
} from "../components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Vận tải</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <FeatureList mt={5} />

      <Statistic mt={5}></Statistic>

      <CallToAction mt={5} />

      <Contact />
    </div>
  );
};

export default Home;
