import { Box } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Script from "next/script";
import {
  CallToAction,
  Contact,
  FeatureList,
  Hero,
  Statistic,
} from "../components";
import { Layout } from "../components/Layouts/Layout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Vận tải</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src="https://cdnjs.com/libraries/bodymovin"
        type="text/javascript"
      ></Script>

      <Layout mx={{ base: 5, md: 14 }}>
        <Hero mt={{ md: 5 }} />

        <FeatureList />

        <Statistic />

        {/* <CallToAction mt={5} /> */}

        <Contact h="100vh" />
      </Layout>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  return {
    props: {}, // will be passed to the page component as props
  };
}
