import { Box } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Hero } from "../components/Heros/Hero";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Vận tải</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <Box h="20rem"></Box>
    </div>
  );
};

export default Home;
